// try {

//     console.log('Начало блока try');  // (1) <--
  
//     //псевдо ошибка (разкоментиировать)
  
//     console.log('Конец блока try (никогда не выполнится при ошибке )');  // (2)
  
//   } catch(err) {
  
//     console.log(`Возникла ошибка!`); // (3) <--
  
//   }
